#!/bin/bash

# Check if a command exists
command_exists() {
    command -v "$1" >/dev/null 2>&1
}

# Get the first available command from the list
get_command() {
    for cmd in "$@"; do
        command_exists "$cmd" && echo "$cmd" && return
    done
}

# Go up `n` directories
cd_up() {
    local n=$1
    while [ "$n" -ne 0 ]; do
        cd ..
        n=$((n - 1))
    done
}

# Source multiple files
source_files() {
    for file in "$@"; do
        [ -f "$file" ] && . "$file"
    done
}

# Add a directory to PATH if it exists and is not already in PATH
pathadd() {
    [ -d "$1" ] && [[ ":$PATH:" != *":$1:"* ]] && PATH="${PATH:+$PATH:}$1"
}

# Initialize a command if it exists
init_command() {
    command_exists "$1" && eval "$($2)"
}

# Git aliases
git_aliases() {
    alias g='git'
    alias gcb='git checkout -b'
    alias gco='git checkout'
    alias gs='git status'
    alias gac='git add -A && git commit -v'
    alias guc='git add -u && git commit -v'
    alias gb='git branch'
    alias gp='git push'
    alias gpl='git pull'
    alias gf='git fetch'
    alias gcp='git cherry-pick'
    alias gcpno='git cherry-pick --no-commit'
    alias gd='git_diff'
}

# Git diff with bat if available
git_diff() {
    if command_exists 'bat'; then
        git diff --name-only --relative --diff-filter=d | xargs bat --diff
    else
        git diff
    fi
}

# Set editor
set_editor() {
    editor="$(get_command hx helix nvim vim vi nano)"
    export EDITOR="$editor"
    export VISUAL="$EDITOR"
}