#!/usr/bin/bash

# ~/.bashrc

# Exit if not running interactively
[[ $- != *i* ]] && return

# Soure functions and aliases
[ -f "$HOME/.bash_functions" ] && . "$HOME/.bash_functions"
[ -f "$HOME/.bash_aliases" ] && . "$HOME/.bash_aliases"

# Set PS1
PS1="\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\] \$ "

pathadd "$HOME/.local/bin"
pathadd "/usr/lib/helix"

set_editor

init_command zoxide "zoxide init bash"
init_command starship "starship init bash"
