#!/bin/bash

function command_exists {
    command -v "$1" >/dev/null 2>&1
}

function get_command {
    for cmd in "$@"; do
        if command_exists "$cmd"; then
            echo "$cmd"
            return
        fi
    done
}

function cd_up {
    local n=$1

    while [ $n -ne 0 ]; do
        cd ..
        n=$((n - 1))
    done
}
