#!/bin/bash

# General Aliases
alias ls='$(get_command exa ls) --color=auto'
alias la='ls -a'
alias l='ls -l'
alias ll='ls -l'
alias l.='ls -a | grep -E "^\\."'

# DIrectory navigation
alias cd='$(get_command z cd)'
alias ..='cd ..'
alias ...='cd ../..'
alias ..3='cd_up 3'
alias ..4='cd_up 4'
alias ..5='cd_up 5'

# Git aliases
git_aliases
