#!/bin/bash

function command_exists {
    command -v "$1" >/dev/null 2>&1
}

function get_command {
    for cmd in "$@"; do
        if command_exists "$cmd"; then
            echo "$cmd"
            return
        fi
    done
}

function cd_up {
    local n=$1

    while [ "$n" -ne 0 ]; do
        cd ..
        n=$((n - 1))
    done
}

function mkdev {
    local environment_dev=$1
    local project_name=$2

    if command_exists "nix"; then
        nix flake new --template "github:the-nix-way/dev-templates#$environment_dev" "$project_name"
    fi
}

function dump_flatpak {
    flatpak list --app --columns=application > ~/Projects/dotfiles/installed_flatpaks.txt
}

function pathadd {
    if [ -d "$1" ] && [[ ":$PATH:" != *":$1:"* ]]; then
        PATH="${PATH:+"$PATH:"}$1"
    fi
}