complete -c ame -n "__fish_use_subcommand" -s c -l cachedir -d 'Sets a custom AUR clone and build directory for the specified operation' -r -f -a "(__fish_complete_directories)"
complete -c ame -n "__fish_use_subcommand" -l help -d 'Print help information'
complete -c ame -n "__fish_use_subcommand" -l version -d 'Print version information'
complete -c ame -n "__fish_use_subcommand" -s v -l verbose -d 'Sets the level of verbosity'
complete -c ame -n "__fish_use_subcommand" -l noconfirm -d 'Complete operation without prompting user'
complete -c ame -n "__fish_use_subcommand" -s q -l quiet -d 'Make some commands have less output'
complete -c ame -n "__fish_use_subcommand" -l sudoloop -d 'Loops sudo in the background to ensure it doesn\'t time out during long builds'
complete -c ame -n "__fish_use_subcommand" -f -a "sync" -d 'Installs or searches for a package in either the AUR or the Pacman-defined repositories'
complete -c ame -n "__fish_use_subcommand" -f -a "remove" -d 'Removes a previously installed package'
complete -c ame -n "__fish_use_subcommand" -f -a "search" -d 'Searches for packages matching a provided pattern in the AUR/repos [aliases: -Ss]'
complete -c ame -n "__fish_use_subcommand" -f -a "query" -d 'Queries installed packages'
complete -c ame -n "__fish_use_subcommand" -f -a "upgrade" -d 'Upgrades locally installed packages to their latest versions (Default)'
complete -c ame -n "__fish_use_subcommand" -f -a "gencomp" -d 'Generates shell completions for supported shells (bash, fish, elvish, pwsh)'
complete -c ame -n "__fish_use_subcommand" -f -a "clean" -d 'Removes all orphaned packages'
complete -c ame -n "__fish_use_subcommand" -f -a "diff" -d 'Runs pacdiff'
complete -c ame -n "__fish_seen_subcommand_from sync" -s b -l by -d 'Searches by a specific field' -r
complete -c ame -n "__fish_seen_subcommand_from sync" -l help -d 'Print help information'
complete -c ame -n "__fish_seen_subcommand_from sync" -l version -d 'Print version information'
complete -c ame -n "__fish_seen_subcommand_from sync" -s a -l aur -d 'Operate only on AUR packages'
complete -c ame -n "__fish_seen_subcommand_from sync" -s r -l repo -d 'Operate only on repo packages'
complete -c ame -n "__fish_seen_subcommand_from sync" -s s -d 'Search packages for a given pattern instead of installing'
complete -c ame -n "__fish_seen_subcommand_from remove" -l help -d 'Print help information'
complete -c ame -n "__fish_seen_subcommand_from remove" -l version -d 'Print version information'
complete -c ame -n "__fish_seen_subcommand_from search" -s b -l by -d 'Searches by a specific field' -r
complete -c ame -n "__fish_seen_subcommand_from search" -l help -d 'Print help information'
complete -c ame -n "__fish_seen_subcommand_from search" -l version -d 'Print version information'
complete -c ame -n "__fish_seen_subcommand_from search" -s a -l aur -d 'Operate only on AUR packages'
complete -c ame -n "__fish_seen_subcommand_from search" -s r -l repo -d 'Operate only on repo packages'
complete -c ame -n "__fish_seen_subcommand_from search" -s s -d 'Search packages for a given pattern instead of installing'
complete -c ame -n "__fish_seen_subcommand_from query" -s i -l info -d 'Get information about a specific package' -r
complete -c ame -n "__fish_seen_subcommand_from query" -l help -d 'Print help information'
complete -c ame -n "__fish_seen_subcommand_from query" -l version -d 'Print version information'
complete -c ame -n "__fish_seen_subcommand_from query" -s a -l aur -d 'Lists AUR/foreign packages [-Qa, -Qm]'
complete -c ame -n "__fish_seen_subcommand_from query" -s r -l repo -d 'Lists repo/native packages [-Qr, -Qn]'
complete -c ame -n "__fish_seen_subcommand_from upgrade" -l help -d 'Print help information'
complete -c ame -n "__fish_seen_subcommand_from upgrade" -l version -d 'Print version information'
complete -c ame -n "__fish_seen_subcommand_from upgrade" -s r -l repo -d 'Upgrades only repo/native packages'
complete -c ame -n "__fish_seen_subcommand_from upgrade" -s a -l aur -d 'Upgrades only from the AUR'
complete -c ame -n "__fish_seen_subcommand_from gencomp" -l help -d 'Print help information'
complete -c ame -n "__fish_seen_subcommand_from gencomp" -l version -d 'Print version information'
complete -c ame -n "__fish_seen_subcommand_from clean" -l help -d 'Print help information'
complete -c ame -n "__fish_seen_subcommand_from clean" -l version -d 'Print version information'
complete -c ame -n "__fish_seen_subcommand_from diff" -l help -d 'Print help information'
complete -c ame -n "__fish_seen_subcommand_from diff" -l version -d 'Print version information'
