# .bash_profile

# Get the aliases and functions
_config_dir=${XDG_CONFIG_HOME:-$HOME/.config}
if [ -f "$_config_dir/bash/bashrc" ]; then
    . "$_config_dir/bash/bashrc"
fi

export HISTFIE="$XDG_DATA_HOME/bash/history"

# User specific environment and startup programs
# source "$CARGO_HOME/env"

eval "$(zoxide init bash)"
eval "$(direnv hook bash)"
eval "$(starship init bash)"
eval "$(fzf --bash)"

eval "$(mise activate bash)"

if [ -f $"HOME/.cache/rye/env" ]; then
  . "$HOME/.cache/rye/env"
fi
