#!/usr/bin/env bash
# $XDG_CONFIG_HOME/bash/bashrc

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# Source global definitions
[ -f "/etc/bashrc" ] && source "/etc/bashrc"

_config_dir=${XDG_CONFIG_HOME:-$HOME/.config}

# Source aliases/functions definitions
while read -r f; do source "$f"; done < <(find "$_config_dir/bash/bashrc.d/" -name "*.sh")

eval "$(direnv hook bash)"
eval "$(tv init bash)"
eval "$(zoxide init bash)"
eval "$(starship init bash)"

bind -x '"\e[Z": fzf_bash_completion'
